### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Whitewolf342** [Gowixx/okuru-free#7]
Not a issue but rather 2 questions.
1. Is it possible to get the whole token of someone with the cmd !token @user. If it is possible how do I do it.
2. Can I use more than one account, like connect the self bot to more than one acc, and how?

**Comment by nekospara** [comment]
1. no
2. try to copy and paste the folder of selfbot and change the token and run it

**Comment by Whitewolf342** [comment]
Ight

**Comment by Gowixx** [comment]
1.) Not possible
2.) Yeah, I'll add multiple token compatability SoonTM
